name: Deploy

permissions:
  contents: read
  pages: write
  id-token: write

on:
  workflow_dispatch:
  push:
    branches: 'main'
    paths:
      - 'content/**'
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
      - name: Checkout the repository.
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            src
            content

      - name: Setup the .NET development environment.
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10

      - name: Restore the project dependencies.
        working-directory: src
        run: dotnet restore

      - name: Build the source directory.
        working-directory: src
        run: dotnet build --no-restore --configuration Release /p:ContinuousIntegrationBuild=true

      - name: Run the Blop generator.
        working-directory: src/Blop
        run: dotnet run --no-build --configuration Release /p:ContinuousIntegrationBuild=true

      - name: Upload the generated output as an artifact.
        uses: actions/upload-artifact@v4
        with:
          path: output


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub pages.
        uses: actions/deploy-pages@v4
